# =========================
# 🌐 The Site Configuration
# =========================

# Import the theme
theme: jekyll-theme-chirpy

# Language & timezone
lang: en
timezone: Asia/Makassar   # kamu bisa ubah sesuai zona waktu lokal

# --------------------------
# 🏷️ Site Identity
# --------------------------

title: Whyu
tagline: Fortis Fortuna Adiuvat - "Keberuntungan berpihak pada yang berani"
description: >-
  Blog pribadi yang membahas pengembangan perangkat lunak, data science, dan eksplorasi teknologi digital.

url: "https://whyursmnn.github.io"
baseurl: ""   # penting: biarkan kosong untuk GitHub Pages

github:
  username: whyursmnn

social:
  name: Wahyu Rusman
  email: wahyurusman31@gmail.com
  links:
    - https://github.com/whyursmnn
    - https://twitter.com/whyursmnn

# --------------------------
# 📊 SEO & Analytics
# --------------------------

webmaster_verifications:
  google:
  bing:

analytics:
  google:
    id:   # isi kalau pakai Google Analytics

pageviews:
  provider:

# --------------------------
# 🎨 Theme & Appearance
# --------------------------

theme_mode: dark   # bisa diganti ke light jika mau default terang
avatar: "assets/images/avatar.jpg"
social_preview_image: "assets/images/avatar.jpg"
cdn:

toc: true

# --------------------------
# 💬 Comments (opsional)
# --------------------------

comments:
  provider:
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:

# --------------------------
# ⚡ PWA (Offline support)
# --------------------------

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

# --------------------------
# ⚙️ Build Settings
# --------------------------

paginate: 10

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
